[params]
    linkTumblr = true
    keywords = "Tierparaden, Stadtmöbel"
    description = "Fotodokumentaion über Tierparaden"

    [params.footer]
        privacy = true

[params.author]
    email = 'mail@christianmahnke.de'
    name = 'Christian Mahnke'
    uri = 'http://www.wikidata.org/entity/Q137668638'
